---
# tasks file for ansible-role-sysctl-conf

- name: /etc/sysctl.conf 
  sysctl:
    name:  "{{ item.k }}"
    value: "{{ item.v }}"
    state: present
    reload: no
  with_items: "{{ sysctl_dict }}"
  tags: [sysctl-conf]

